export const KOI_MANAGEMENT_HEADER = [
  "Id",
  "Name",
  "Sex",
  "Length",
  "Year Born",
  "Thumbnail",
  "Base Price",
  "Status",
  "Display",
  "Owner ID",
  "Category ID",
  "Actions",
];

export const BREEDER_KOI_MANAGEMENT_HEADER = [
  "Id",
  "Name",
  "Sex",
  "Length",
  "Year Born",
  "Thumbnail",
  "Base Price",
  "Status",
  "Category ID",
  "Actions",
];

export const STAFF_MANAGEMENT_HEADER = [
  "Id",
  "Staff",
  "Full Name",
  "Phone Number",
  "Email",
  "Address",
  "Status",
  "Active",
  "Subscription",
  "Date of Birth",
  "Balance",
  "Number of Auctions",
  "Created At",
  "Updated At",
  "Actions",
];

export const BREEDER_MANAGEMENT_HEADER = [
  "ID",
  "Breeder",
  "Email",
  "Phone Number",
  "Address",
  "Status",
  "Active",
  "Subscription",
  "Balance",
  "Total Koi",
  "Created At",
  "Updated At",
  "Actions",
];

export const MEMBER_MANAGEMENT_HEADER = [
  "ID",
  "Member",
  "First Name",
  "Last Name",
  "Phone Number",
  "Email",
  "Address",
  "Status",
  "Active",
  "Subscription",
  "Date of Birth",
  "Balance",
  "Total Orders",
  "Created At",
  "Updated At",
  "Actions",
];

export const AUCTION_KOI_HEADER = [
  "Id",
  "Auction Id",
  "Koi Id",
  "Base Price",
  "Current Bid",
  "Current Bidder Id",
  "Is Sold",
  "Bid Method",
  "Bid Step",
];
