name: CD for Koi-Auction-FE

on:
  push:
    branches: [ "main", "production" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build the project
        run: npm run build
      
      - name: Deploy to Production Repo
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configure Git
          git config --global user.name "lcaohoanq"
          git config --global user.email "hoangclw@gmail.com"
          
          # Set up SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          
          # Add GitHub to known hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          # Clone the production repository
          git clone git@github.com:lcaohoanq/Koi-Auction-Production.git production-repo
          
          # Copy new build files
          cp -r dist/* production-repo/
          
          # Commit and push changes
          cd production-repo
          git add .
          git commit -m "Deploy new build from ${{ github.ref_name }} branch"
          git push origin main
